exclude: '^.*\.html*$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-docstring-first
    - id: check-yaml
      exclude: ^kubernetes/|^applications/|^helm/
      args:
        - --unsafe
    - id: end-of-file-fixer
      exclude: ^kubernetes/|^applications/|^helm/
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md,markdown"]
      exclude: CHANGELOG.md
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: [
          '--include', 'api'
        ]
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.17.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
