# Generated by Django 3.1.1 on 2022-10-05 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20221005_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('data', models.DateField()),
                ('status', models.IntegerField()),
                ('descricao', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('usuario_logado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicos_ordemservico_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviços',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('usuario_logado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicos_tiposervico_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged')),
            ],
            options={
                'verbose_name': 'tipo serviço',
                'verbose_name_plural': 'tipos de serviços',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('descricao', models.CharField(max_length=100)),
                ('codigo_erp', models.IntegerField(blank=True, null=True)),
                ('usuario_logado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicos_servico_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('tempo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.ordemservico')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.atendente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicos.tiposervico')),
                ('usuario_logado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicos_ordemservicotecnico_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged')),
            ],
            options={
                'verbose_name': 'técnico da ordem de serviço',
                'verbose_name_plural': 'técnicos das ordens de serviços',
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tempo', models.IntegerField(blank=True, default=1, null=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
                ('usuario_logado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicos_ordemservicoitem_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged')),
            ],
            options={
                'verbose_name': 'item da ordem de serviço',
                'verbose_name_plural': 'itens das ordens de serviços',
            },
        ),
    ]
