# Generated by Django 3.1.1 on 2022-10-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.IntegerField(choices=[(1, 'Iniciada'), (2, 'Em Execução'), (3, 'Finalizada'), (9, 'Cancelada')], default=1),
        ),
    ]
