# Generated by Django 3.1.1 on 2022-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20221005_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoitem',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
