# Generated by Django 3.1.1 on 2022-10-07 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0003_ordemservicoitem_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='usuario_encerramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_encerramento', to=settings.AUTH_USER_MODEL),
        ),
    ]
