# Generated by Django 3.1.1 on 2022-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20221007_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='gerar_integracao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
