# Generated by Django 3.1.1 on 2022-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_ordemservico_gerar_integracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='gerar_integracao',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
