# Generated by Django 3.1.1 on 2022-10-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0006_auto_20221010_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_cancelamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
