# Generated by Django 4.1.5 on 2023-01-26 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0007_auto_20221011_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged'),
        ),
        migrations.AlterField(
            model_name='ordemservicotecnico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordemservicotecnico',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged'),
        ),
    ]
