# Generated by Django 3.1.1 on 2022-10-04 14:12

import chamados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=chamados.models.user_directory_path)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('termino', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Urgente')], default='NORMAL', max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('ESTAMOS_TRABALHANDO', 'Estamos trabalhando'), ('PRECISAMOS_INFORMACOES', 'Precisamos de informações'), ('AGUARDANDO_CLIENTE', 'Aguardando Cliente'), ('PROXIMA_VERSAO', 'Sairá na proxima versão'), ('RESOLVIDO', 'Resolvido pelo Atendente'), ('FINALIZADO', 'Finalizado')], default='INICIADO', max_length=50)),
                ('departamento', models.CharField(choices=[('SUPORTE', 'Suporte'), ('COMERCIAL', 'Comercial'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('FINANCEIRO', 'Financeiro')], default='SUPORTE', max_length=50)),
                ('versao', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel', models.IntegerField(choices=[(1, 'Suporte 1'), (2, 'Suporte 2'), (3, 'Suporte 3')], default=1)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketInteracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('descricao', models.TextField()),
                ('interno', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('ESTAMOS_TRABALHANDO', 'Estamos trabalhando'), ('PRECISAMOS_INFORMACOES', 'Precisamos de informações'), ('AGUARDANDO_CLIENTE', 'Aguardando Cliente'), ('PROXIMA_VERSAO', 'Sairá na proxima versão'), ('RESOLVIDO', 'Resolvido pelo Atendente'), ('FINALIZADO', 'Finalizado')], default='ESTAMOS_TRABALHANDO', max_length=50)),
                ('departamento', models.CharField(choices=[('SUPORTE', 'Suporte'), ('COMERCIAL', 'Comercial'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('FINANCEIRO', 'Financeiro')], default='SUPORTE', max_length=50)),
                ('arquivos', models.ManyToManyField(blank=True, to='chamados.Anexo')),
            ],
            options={
                'verbose_name': 'interação',
                'verbose_name_plural': 'interações',
                'ordering': ('id',),
            },
        ),
    ]
