# Generated by Django 3.1.1 on 2022-10-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('chamados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinteracao',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.atendente'),
        ),
        migrations.AddField(
            model_name='ticketinteracao',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.ticket'),
        ),
        migrations.AddField(
            model_name='ticketinteracao',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chamados_ticketinteracao_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='arquivos',
            field=models.ManyToManyField(blank=True, to='chamados.Anexo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.atendente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chamados_ticket_logged_user', to=settings.AUTH_USER_MODEL, verbose_name='user in logged'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
