# Generated by Django 3.1.1 on 2022-10-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20221007_1310'),
        ('chamados', '0002_auto_20221004_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servicos.ordemservico'),
        ),
    ]
