# Generated by Django 3.1.1 on 2022-10-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221005_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('clientes', models.ManyToManyField(to='core.Cliente')),
            ],
        ),
    ]
