# Generated by Django 3.1.1 on 2022-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocliente',
            name='clientes',
            field=models.ManyToManyField(blank=True, null=True, to='core.Cliente'),
        ),
    ]
